-- local BACKGROUND_COLOR = vmath.vector4(252/255, 223/255, 205/255, 255/255)
-- local BACKGROUND_COLOR = vmath.vector4(72/255, 159/255, 181/255, 255/255)
local BACKGROUND_COLOR = vmath.vector4(130/255, 192/255, 204/255, 255/255)
function init(self)
	-- msg.post("@render:", "use_fixed_projection", { zoom = 3, near = -10, far = 10 })
	msg.post("@render:", "clear_color", { color = BACKGROUND_COLOR })
end
